# Generated by Django 4.2.30 on 2026-06-26 19:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETAIRE', 'Secrétaire'), ('DIRECTEUR', 'Directeur'), ('CHEF_DIVISION', 'Chef de division'), ('CHEF_SECTION', 'Chef de section'), ('AGENT', 'Agent')], default='AGENT', max_length=20, verbose_name='Rôle')),
                ('fonction', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=30, unique=True, verbose_name='NIF')),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('activite', models.CharField(blank=True, max_length=255, verbose_name='Activité')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('regime', models.CharField(blank=True, max_length=100, verbose_name='Régime fiscal')),
            ],
            options={
                'verbose_name': 'Contribuable',
                'verbose_name_plural': 'Contribuables',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('ENTRANT', 'Entrant'), ('SORTANT', 'Sortant')], default='ENTRANT', max_length=10, verbose_name='Type')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_courrier', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du courrier')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('statut', models.CharField(choices=[('ENREGISTRE', 'Enregistré'), ('EN_AFFECTATION', "En cours d'affectation"), ('EN_TRAITEMENT', 'En traitement'), ('EN_VALIDATION', 'En validation'), ('PRET_ENVOI', 'Prêt à envoyer'), ('ENVOYE', 'Envoyé au contribuable')], default='ENREGISTRE', max_length=20, verbose_name='Statut')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('date_archivage', models.DateTimeField(blank=True, null=True, verbose_name='Archivé le')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers', to='courriers.contribuable', verbose_name='Contribuable')),
                ('courrier_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='courriers.courrier', verbose_name="Courrier d'origine")),
                ('detenteur_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_en_charge', to=settings.AUTH_USER_MODEL, verbose_name='Détenteur actuel')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('type', models.CharField(choices=[('DIRECTION', 'Direction'), ('DIVISION', 'Division'), ('SECTION', 'Section')], max_length=20, verbose_name='Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='courriers.structure', verbose_name='Structure parente')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='courriers/%Y/%m/', verbose_name='Fichier scanné')),
                ('libelle', models.CharField(blank=True, max_length=200, verbose_name='Libellé')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='courriers.courrier')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courriers.courrier')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Acheminement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENREGISTREMENT', 'Enregistrement'), ('AFFECTATION', 'Affectation'), ('TRAITEMENT', 'Traitement'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet / renvoi pour correction'), ('ENVOI', 'Envoi au contribuable')], max_length=20, verbose_name='Action')),
                ('sens', models.CharField(blank=True, choices=[('DESCENDANT', 'Descendant'), ('REMONTANT', 'Remontant')], max_length=12, verbose_name='Sens')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire / instructions')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheminements', to='courriers.courrier')),
                ('de_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='De')),
                ('vers_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vers')),
            ],
            options={
                'verbose_name': 'Acheminement',
                'verbose_name_plural': 'Acheminements',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='courriers.structure', verbose_name='Structure de rattachement'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
