# Generated by Django 4.2.30 on 2026-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejointe',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='courriers/%Y/%m/', verbose_name='Fichier scanné'),
        ),
    ]
